const arenamindFAQ = [
    "What is Arenamind AI? Arenamind AI builds smart, affordable AI tools that help small businesses grow through automation, customer engagement, and 24/7 support.",
    "What does Arenamind mean? It represents a creative, arena-like space for powerful, collaborative minds using AI to make business easier.",
    "Where are you located? We’re a remote-first startup based in the U.S., with team members across several states.",
    "What industries do you serve? We work with small businesses across healthcare, beauty, fitness, retail, real estate, and service industries.",
    "Do you only work with small businesses? Mostly, yes. We specialize in helping small to mid-sized teams automate customer communication affordably.",
    "How long have you been around? Arenamind AI was founded in 2025 by a small group of developers and designers passionate about AI and small business growth.",
    "Is Arenamind AI a chatbot company? Not exactly — we’re an AI automation company that builds receptionist, follow-up, and engagement systems that feel human.",
    "What makes you different from other AI tools? Our tools are designed specifically for small businesses — quick to set up, affordable, and tailored to your tone and brand.",
    "Do you have human support? Absolutely! Every client gets direct support and a real person to help set up and tune their AI.",
    "Can I see a demo? Yes — we offer short live demos where you can see how the AI handles calls, texts, and scheduling in real time.",
    "What does the AI receptionist do? It answers calls or chats 24/7, greets customers, answers FAQs, books appointments, and captures lead information.",
    "Can it transfer calls to a human? Yes — it can route calls or take a message and notify your team automatically.",
    "Does it sound human? Very much so! You can even choose between different voice styles to match your brand.",
    "Can it handle multiple locations? Yes, the Pro plan supports multi-location routing and calendars.",
    "How does it learn my business info? We set it up with your FAQs, hours, pricing, and tone during onboarding.",
    "Can it handle both voice and chat? Yes — it works for phone, website chat, or SMS conversations.",
    "What if it can’t answer a question? It politely says it will have a team member follow up and logs the question for improvement.",
    "Is the AI receptionist secure? Yes — all calls, messages, and data are encrypted and never shared with third parties.",
    "Can I listen to recordings or see transcripts? Yes, transcripts are available for review inside your dashboard.",
    "How quickly can it be set up? Usually within 48-72 hours after onboarding.",
    "Can it book appointments? Yes — it connects to Google Calendar or your booking system to schedule or reschedule appointments.",
    "Can it handle multiple staff members’ calendars? Yes — the Growth and Pro plans support multiple users and synced schedules.",
    "How does it avoid double-booking? It checks your calendar availability in real time before confirming appointments.",
    "Can it send reminders to customers? Yes — confirmation and reminder texts or emails are automatically sent.",
    "What if a customer cancels? The AI updates your calendar and can automatically offer the next available time.",
    "What is the Follow-Up Flow? It’s an automated system that sends personalized thank-yous, feedback requests, and rebooking prompts after a customer visit.",
    "Can I customize the follow-up messages? Yes — you can edit tone, content, and timing to fit your business voice.",
    "Does it send SMS or email? Both! You can choose one or combine them.",
    "Can it help get Google Reviews? Yes — it can politely ask happy clients to leave a review and guide them to your review link.",
    "Can it detect unhappy customers? It uses sentiment cues to flag negative feedback and alert your team.",
    "Can it follow up with cold leads? Yes — it can re-engage leads who never booked or haven’t responded in a while.",
    "How much does it cost? Plans start at $399/month and scale up to $1,499/month for full automation and engagement.",
    "Do you offer a free trial? We offer a live demo and short trial period during onboarding for qualified businesses.",
    "Is there a setup fee? Yes — a one-time $199 setup fee covers configuration, training, and voice customization.",
    "Can I cancel anytime? Yes — all plans are month-to-month, with no long-term contracts.",
    "What’s included in each plan? Each higher tier adds more automation: Starter (calls), Growth (follow-ups), Pro (retention + full analytics).",
    "Why is the Pro plan best? It includes unlimited conversations, a dedicated manager, and advanced engagement flows — maximizing ROI.",
    "Are there discounts for multiple locations? Yes — multi-location businesses get a bundled rate on the Pro plan.",
    "How do payments work? We bill monthly via secure credit card or ACH.",
    "Do you offer custom packages? Yes — we can tailor a plan for unique use cases or integrations.",
    "Does it integrate with my CRM? Yes — we connect with HubSpot, Airtable, or Notion, and can add custom integrations.",
    "Does it support text-to-speech and speech-to-text? Yes — that’s how it handles phone calls naturally.",
    "Is my data private? Absolutely. We never sell or share your data; everything is securely stored.",
    "Can it connect with Twilio? Yes — Twilio powers the voice and messaging layer for reliability and scale.",
    "Can it send messages in other languages? Yes — multilingual support is available as an add-on.",
    "Can I train it on my own FAQs? Yes — you can provide up to 100 custom FAQs per location.",
    "Can it recognize repeat customers? Yes — the CRM sync helps it remember returning clients for a more personal touch.",
    "Does it use OpenAI? Yes — it runs on OpenAI’s secure models, fine-tuned for business interactions.",
    "What if something goes wrong? You’ll have 24/7 support plus a human contact who can jump in anytime.",
    "How do I get started? Book a demo on our website or contact us to start your onboarding call — setup takes just a day or two."
];

module.exports = { arenamindFAQ };  